### ISSUE TITLE
bump request: qliveplayer

### ISSUE THREAD

**Issue by jian-lin** [berberman/flakes#19] opened 2021-09-16 05:08 UTC
Hi, thanks for your work! qliveplayer-4.0 uses rust instead of python. Could you bump to that version, please?

**Comment by berberman** [comment] 2021-09-16 05:17
Hi, the version of this package was pinned (#16), because nvfetcher's workflow needs Cargo.lock in the upstream repo: https://github.com/IsoaSFlus/QLivePlayer-Lib

**Comment by jian-lin** [comment] 2021-09-16 05:25
I see. Feel free to close this issue.

**Comment by berberman** [comment] 2021-09-16 05:36
I would not close this as the issue is not yet  resolved. We may report this to the upstream, since rust applications should have cargo lock files conventionally.

**Comment by jian-lin** [comment] 2021-09-16 05:42
FYI. The author [says](https://github.com/IsoaSFlus/QLivePlayer/issues/30#issuecomment-898992846) he **will** add the lock file.

**Comment by jian-lin** [comment] 2021-10-10 02:16
[qliveplayer-4.1.0](https://github.com/THMonster/QLivePlayer/releases/tag/4.1.0) depends on [qliveplayer-lib-0.5.0](https://github.com/THMonster/QLivePlayer-Lib/commit/1d8c90d4939ce54316fce1f77a77e1950cffe66a) which has a `Cargo.lock`.

**Closed as completed** 2022-01-02 03:39 UTC
